/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControleCurtidas;
import javax.swing.JPanel;
import model.Usuarios;

/**
 *
 * @author rocal
 */
public class Curtidas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Curtidas.class.getName());

    private Usuarios usuario;
    private ControleCurtidas c;

    public Curtidas(Usuarios usuario) {
        initComponents();

        this.usuario = usuario;

        c = new ControleCurtidas(this, usuario);
        c.carregarCurtidas();
        
        btn_voltarCurtidas.addActionListener(e -> {
            this.setVisible(false);
        });
    }

    public JPanel getPainelCurtidas() {
        return painelCurtidas;
    }
            
        
        


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_voltarCurtidas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        painelCurtidas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_voltarCurtidas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_voltarCurtidas.setText("Voltar");
        btn_voltarCurtidas.addActionListener(this::btn_voltarCurtidasActionPerformed);

        javax.swing.GroupLayout painelCurtidasLayout = new javax.swing.GroupLayout(painelCurtidas);
        painelCurtidas.setLayout(painelCurtidasLayout);
        painelCurtidasLayout.setHorizontalGroup(
            painelCurtidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );
        painelCurtidasLayout.setVerticalGroup(
            painelCurtidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(painelCurtidas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_voltarCurtidas)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btn_voltarCurtidas)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarCurtidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarCurtidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_voltarCurtidasActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Curtidas().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_voltarCurtidas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painelCurtidas;
    // End of variables declaration//GEN-END:variables
}
