/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControleVideosDaLista;
import model.Usuarios;
import javax.swing.JPanel;
/**
 *
 * @author rocal
 * 
 */



public class VideosDaLista extends javax.swing.JFrame {
    private Usuarios usuario;
    private int listaId;
    private ControleVideosDaLista c;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VideosDaLista.class.getName());

    /**
     * Creates new form VideosDaLista
     */
    public VideosDaLista(Usuarios usuario, int listaId, String nomeLista) {
    initComponents();
    this.usuario = usuario;
    this.listaId = listaId;
    lbl_titulo.setText(nomeLista);
    c = new ControleVideosDaLista(this, usuario, listaId);
    c.carregarVideos();
}

public JPanel getPainelVideos() {
    return painelVideos;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        lbl_titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        painelVideos = new javax.swing.JPanel();
        txt_buscar = new javax.swing.JTextField();
        lbl_buscar = new javax.swing.JLabel();
        btn_adicionar = new javax.swing.JToggleButton();
        btn_voltar = new javax.swing.JToggleButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_titulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_titulo.setText("jLabel1");

        javax.swing.GroupLayout painelVideosLayout = new javax.swing.GroupLayout(painelVideos);
        painelVideos.setLayout(painelVideosLayout);
        painelVideosLayout.setHorizontalGroup(
            painelVideosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );
        painelVideosLayout.setVerticalGroup(
            painelVideosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(painelVideos);

        lbl_buscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_buscar.setText("Buscar:");

        btn_adicionar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_adicionar.setText("Adicionar  +");
        btn_adicionar.addActionListener(this::btn_adicionarActionPerformed);

        btn_voltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(this::btn_voltarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lbl_titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_adicionar)
                                .addGap(391, 391, 391)
                                .addComponent(btn_voltar))
                            .addComponent(lbl_buscar)
                            .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lbl_titulo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_buscar)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_voltar)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_adicionar)
                        .addContainerGap(17, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        Lista tela = new Lista(usuario);
        tela.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void btn_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adicionarActionPerformed
        String busca = txt_buscar.getText();
        if (!busca.trim().isEmpty()) {
            c.adicionarVideo(busca);
        }// TODO add your handling code here:
    }//GEN-LAST:event_btn_adicionarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new VideosDaLista().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_adicionar;
    private javax.swing.JToggleButton btn_voltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lbl_buscar;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPanel painelVideos;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables
}
