/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.ControleLogado;
import model.Usuarios;
import view.Lista;

/**
 *
 * @author rocal
 */
public class Logado extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Logado.class.getName());

    /**
     * Creates new form Logado
     */
    public Logado(Usuarios usuario) {
        initComponents();
        this.usuario = usuario;
        c = new ControleLogado(this, usuario);
    }

    public Logado() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_fei = new javax.swing.JLabel();
        lbl_buscar = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        btn_curtidas = new javax.swing.JButton();
        btn_listas = new javax.swing.JButton();
        btn_sair = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_fei.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_fei.setText("FEITV!");

        lbl_buscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_buscar.setText("Busque por um video!");

        btn_buscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(this::btn_buscarActionPerformed);

        btn_curtidas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_curtidas.setText("Visualizar Curtidas");
        btn_curtidas.addActionListener(this::btn_curtidasActionPerformed);

        btn_listas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_listas.setText("Visualizar Listas");
        btn_listas.addActionListener(this::btn_listasActionPerformed);

        btn_sair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_sair.setText("Sair");
        btn_sair.setActionCommand("");
        btn_sair.addActionListener(this::btn_sairActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(lbl_fei))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(lbl_buscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btn_curtidas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_listas))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(btn_buscar)))))
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_sair)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btn_sair)
                .addGap(30, 30, 30)
                .addComponent(lbl_fei)
                .addGap(34, 34, 34)
                .addComponent(lbl_buscar)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_curtidas)
                    .addComponent(btn_listas))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        String nome = txt_buscar.getText();
        c.buscarPorNome(nome);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_curtidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_curtidasActionPerformed
        Curtidas tela = new Curtidas(usuario);
        tela.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btn_curtidasActionPerformed

    private void btn_listasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listasActionPerformed
        Lista tela = new Lista(usuario);
        tela.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btn_listasActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_btn_sairActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Logado().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_curtidas;
    private javax.swing.JButton btn_listas;
    private javax.swing.JToggleButton btn_sair;
    private javax.swing.JLabel lbl_buscar;
    private javax.swing.JLabel lbl_fei;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables
    private ControleLogado c;
    private Usuarios usuario;

}


