/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.ControleResultadoBusca;
import model.Usuarios;
import view.Logado;



/**
 *
 * @author rocal
 */
public class ResultadoBusca extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ResultadoBusca.class.getName());

    /**
     * Creates new form ResultadoBusca
     */
    private Usuarios usuario;
    private int videoId;
    
    
    public ResultadoBusca(Usuarios usuario, int videoId, String titulo, String ano, String duracao, String tipo) {
        initComponents();
        c = new ControleResultadoBusca(this, usuario, videoId);

        
        
        this.usuario = usuario;
        this.videoId = videoId;
        
        lblTitulo.setText(titulo);
        lblAno.setText(ano);
        lblDuracao.setText(duracao);
        lblTipo.setText(tipo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lbl_busca = new javax.swing.JLabel();
        lblAno = new javax.swing.JLabel();
        lblDuracao = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        btn_voltar = new javax.swing.JButton();
        btn_curtir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitulo.setText("Título:");

        lbl_busca.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_busca.setText("Sua busca:");

        lblAno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAno.setText("Ano:");

        lblDuracao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDuracao.setText("Duração:");

        lblTipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTipo.setText("Tipo:");

        btn_voltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(this::btn_voltarActionPerformed);

        btn_curtir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_curtir.setText("Curtir");
        btn_curtir.addActionListener(this::btn_curtirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipo)
                    .addComponent(lblTitulo)
                    .addComponent(lbl_busca)
                    .addComponent(lblAno)
                    .addComponent(lblDuracao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btn_curtir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 371, Short.MAX_VALUE)
                .addComponent(btn_voltar)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_busca)
                .addGap(43, 43, 43)
                .addComponent(lblTitulo)
                .addGap(31, 31, 31)
                .addComponent(lblAno)
                .addGap(37, 37, 37)
                .addComponent(lblDuracao)
                .addGap(44, 44, 44)
                .addComponent(lblTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_voltar)
                    .addComponent(btn_curtir))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        Logado tela = new Logado(usuario);  
        tela.setVisible(true);       
        this.dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void btn_curtirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_curtirActionPerformed
        c.curtirVideo();// TODO add your handling code here:
    }//GEN-LAST:event_btn_curtirActionPerformed
    private ControleResultadoBusca c;
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new ResultadoBusca().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_curtir;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblDuracao;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lbl_busca;
    // End of variables declaration//GEN-END:variables
}
